import { Settings } from '../../../entities/settings'

export interface SettingsEvents {
  SETTINGS_FETCH
  SETTINGS_UPDATE_NICKNAME
  SETTINGS_UPDATE_GAME_DIRECTORY
  SETTINGS_UPDATE_AUTO_SWITCH_NICKNAME
  SETTINGS_UPDATE_DELETION_CONFIRM
  SETTINGS_UPDATE_SERVER_REFRESH_DELAY
  SETTINGS_UPDATE_REFRESH_ALL_SERVERS
  SETTINGS_UPDATE_EXTRA_INJECT
}

export interface SettingsEventsPayload {
  SETTINGS_FETCH
  SETTINGS_UPDATE_NICKNAME: string
  SETTINGS_UPDATE_GAME_DIRECTORY: string
  SETTINGS_UPDATE_AUTO_SWITCH_NICKNAME
  SETTINGS_UPDATE_DELETION_CONFIRM: boolean
  SETTINGS_UPDATE_SERVER_REFRESH_DELAY: number
  SETTINGS_UPDATE_REFRESH_ALL_SERVERS: boolean
  SETTINGS_UPDATE_EXTRA_INJECT: string[]
}

export interface SettingsEventsReturns {
  SETTINGS_FETCH: Settings
  SETTINGS_UPDATE_NICKNAME
  SETTINGS_UPDATE_GAME_DIRECTORY
  SETTINGS_UPDATE_AUTO_SWITCH_NICKNAME
  SETTINGS_UPDATE_DELETION_CONFIRM
  SETTINGS_UPDATE_SERVER_REFRESH_DELAY
  SETTINGS_UPDATE_REFRESH_ALL_SERVERS
  SETTINGS_UPDATE_EXTRA_INJECT
}
